CREATE TABLE `magneto`.`DNA` (
  `DNA_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `DNA_VALUE` MEDIUMTEXT NOT NULL,
  `DNA_MUTANT` TINYINT NOT NULL,
  PRIMARY KEY (`DNA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;