server:
  port: 8080
logging:
  format: TEXT
  level:
    org:
      springframework:
        data:
          r2dbc: ERROR
spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/magneto
    pool:
      max-size: 15
      max-idle-time: 10m
      validation-query: SELECT 1
    username: root
    password: admin1234
    name: magneto
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true

